version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: >
      sh -c "flask db init || true &&
             flask db migrate -m 'Initial migration' || true &&
             flask db upgrade || true &&
             flask run --host=0.0.0.0 --port=5000"